-- Schema and index updates for middleware_bill_with_putaway_true and log_bill_with_putaway_true

CREATE TABLE IF NOT EXISTS middleware_bill_with_putaway_true (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  bill_id INT(11) DEFAULT NULL,
  bill_no VARCHAR(100) DEFAULT NULL,
  contact_id INT(11) DEFAULT NULL,
  supplier_name VARCHAR(255) DEFAULT NULL,
  transaction_date DATETIME DEFAULT NULL,
  created_date DATETIME DEFAULT NULL,
  due_date DATETIME DEFAULT NULL,
  is_tax_included TINYINT(1) DEFAULT 0,
  note TEXT DEFAULT NULL,
  sub_total DECIMAL(18,4) DEFAULT NULL,
  total_disc DECIMAL(18,4) DEFAULT NULL,
  total_tax DECIMAL(18,4) DEFAULT NULL,
  grand_total DECIMAL(18,4) DEFAULT NULL,
  ref_no VARCHAR(100) DEFAULT NULL,
  is_opening_balance TINYINT(1) DEFAULT 0,
  payment DECIMAL(18,4) DEFAULT NULL,
  payment_acct_id INT(11) DEFAULT NULL,
  location_id INT(11) DEFAULT NULL,
  purchaseorder_id INT(11) DEFAULT NULL,
  last_modified DATETIME DEFAULT NULL,
  is_consignment TINYINT(1) DEFAULT 0,
  created_by VARCHAR(100) DEFAULT NULL,
  payment_term VARCHAR(100) DEFAULT NULL,
  auto_placement TINYINT(1) DEFAULT 0,
  attachment TEXT DEFAULT NULL,
  add_cost DECIMAL(18,4) DEFAULT NULL,
  updated_by VARCHAR(100) DEFAULT NULL,
  tag_ids TEXT DEFAULT NULL,
  header_note TEXT DEFAULT NULL,
  is_closed TINYINT(1) DEFAULT 0,
  purchaseorder_no VARCHAR(100) DEFAULT NULL,
  location_name VARCHAR(255) DEFAULT NULL,
  payment_amount DECIMAL(18,4) DEFAULT NULL,
  add_cost_detail LONGTEXT DEFAULT NULL,
  is_putaway TINYINT(1) DEFAULT 0,
  items_payload LONGTEXT DEFAULT NULL,
  payload LONGTEXT DEFAULT NULL,
  status ENUM('pending','sent','failed') NOT NULL DEFAULT 'pending',
  response LONGTEXT DEFAULT NULL,
  sent_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  INDEX idx_bill_no (bill_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS log_bill_with_putaway_true (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  source_id INT(11) DEFAULT NULL,
  action VARCHAR(64) NOT NULL,
  message TEXT DEFAULT NULL,
  meta TEXT DEFAULT NULL,
  ip VARCHAR(45) DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT current_timestamp(),
  INDEX idx_log_bill_source_id (source_id),
  INDEX idx_log_bill_action (action),
  INDEX idx_log_bill_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
