-- Create detail table for penjualan lines linked by salesorder_no
CREATE TABLE IF NOT EXISTS middleware_penjualan_detail (
  id INT AUTO_INCREMENT PRIMARY KEY,
  salesorder_no VARCHAR(100) NOT NULL,
  salesorder_detail_id INT DEFAULT NULL,
  item_id INT DEFAULT NULL,
  item_code VARCHAR(100) DEFAULT NULL,
  item_name VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  barcode VARCHAR(100) DEFAULT NULL,
  qty DECIMAL(18,4) DEFAULT NULL,
  qty_in_base DECIMAL(18,4) DEFAULT NULL,
  unit VARCHAR(50) DEFAULT NULL,
  uom_id INT DEFAULT NULL,
  price DECIMAL(18,4) DEFAULT NULL,
  sell_price DECIMAL(18,4) DEFAULT NULL,
  original_price DECIMAL(18,4) DEFAULT NULL,
  amount DECIMAL(18,4) DEFAULT NULL,
  disc DECIMAL(18,4) DEFAULT NULL,
  disc_amount DECIMAL(18,4) DEFAULT NULL,
  disc_marketplace DECIMAL(18,4) DEFAULT NULL,
  tax_id INT DEFAULT NULL,
  tax_name VARCHAR(100) DEFAULT NULL,
  tax_amount DECIMAL(18,4) DEFAULT NULL,
  rate DECIMAL(18,4) DEFAULT NULL,
  weight_in_gram DECIMAL(18,4) DEFAULT NULL,
  item_group_id INT DEFAULT NULL,
  loc_id INT DEFAULT NULL,
  loc_name VARCHAR(150) DEFAULT NULL,
  thumbnail VARCHAR(255) DEFAULT NULL,
  is_bundle TINYINT(1) DEFAULT 0,
  is_fbm TINYINT(1) DEFAULT 0,
  fbm VARCHAR(50) DEFAULT NULL,
  serials TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  INDEX idx_salesorder_no (salesorder_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
