-- Schema update for middleware_penjualan_cancel to support richer Jubelio cancel payload
CREATE TABLE IF NOT EXISTS middleware_penjualan_cancel (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_no VARCHAR(100) DEFAULT NULL,
  salesorder_id INT DEFAULT NULL,
  salesorder_no VARCHAR(100) DEFAULT NULL,
  contact_id INT DEFAULT NULL,
  customer_name VARCHAR(255) DEFAULT NULL,
  customer_phone VARCHAR(50) DEFAULT NULL,
  customer_email VARCHAR(255) DEFAULT NULL,
  transaction_date DATETIME DEFAULT NULL,
  created_date DATETIME DEFAULT NULL,
  last_modified DATETIME DEFAULT NULL,
  is_tax_included TINYINT(1) DEFAULT 0,
  note TEXT DEFAULT NULL,
  sub_total DECIMAL(18,4) DEFAULT NULL,
  total_disc DECIMAL(18,4) DEFAULT NULL,
  total_tax DECIMAL(18,4) DEFAULT NULL,
  grand_total DECIMAL(18,4) DEFAULT NULL,
  ref_no VARCHAR(100) DEFAULT NULL,
  payment_method VARCHAR(100) DEFAULT NULL,
  location_id INT DEFAULT NULL,
  is_canceled TINYINT(1) DEFAULT 0,
  cancel_reason VARCHAR(255) DEFAULT NULL,
  cancel_reason_detail VARCHAR(255) DEFAULT NULL,
  source VARCHAR(100) DEFAULT NULL,
  is_paid TINYINT(1) DEFAULT 0,
  channel_status VARCHAR(100) DEFAULT NULL,
  shipping_cost DECIMAL(18,4) DEFAULT NULL,
  insurance_cost DECIMAL(18,4) DEFAULT NULL,
  shipping_full_name VARCHAR(255) DEFAULT NULL,
  shipping_address VARCHAR(255) DEFAULT NULL,
  shipping_area VARCHAR(150) DEFAULT NULL,
  shipping_city VARCHAR(150) DEFAULT NULL,
  shipping_province VARCHAR(150) DEFAULT NULL,
  shipping_post_code VARCHAR(50) DEFAULT NULL,
  shipping_country VARCHAR(100) DEFAULT NULL,
  shipping_phone VARCHAR(50) DEFAULT NULL,
  tracking_number VARCHAR(150) DEFAULT NULL,
  courier VARCHAR(150) DEFAULT NULL,
  service_fee DECIMAL(18,4) DEFAULT NULL,
  buyer_shipping_cost DECIMAL(18,4) DEFAULT NULL,
  package_count INT DEFAULT NULL,
  wms_status VARCHAR(100) DEFAULT NULL,
  shipping_cost_discount DECIMAL(18,4) DEFAULT NULL,
  discount_marketplace DECIMAL(18,4) DEFAULT NULL,
  internal_cancel_date DATETIME DEFAULT NULL,
  tracking_url VARCHAR(255) DEFAULT NULL,
  cod_fee DECIMAL(18,4) DEFAULT NULL,
  total_weight_in_kg DECIMAL(18,4) DEFAULT NULL,
  internal_status VARCHAR(100) DEFAULT NULL,
  invoice_id INT DEFAULT NULL,
  invoice_no VARCHAR(100) DEFAULT NULL,
  invoice_date DATETIME DEFAULT NULL,
  salesmen_name VARCHAR(255) DEFAULT NULL,
  tracking_no VARCHAR(150) DEFAULT NULL,
  source_name VARCHAR(100) DEFAULT NULL,
  store_name VARCHAR(150) DEFAULT NULL,
  location_name VARCHAR(150) DEFAULT NULL,
  location_code VARCHAR(100) DEFAULT NULL,
  picklist_no VARCHAR(100) DEFAULT NULL,
  channel_id INT DEFAULT NULL,
  store VARCHAR(100) DEFAULT NULL,
  status VARCHAR(100) DEFAULT NULL,
  cancel_date DATETIME DEFAULT NULL,
  payload LONGTEXT DEFAULT NULL,
  items_payload LONGTEXT DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  INDEX idx_order_no (order_no),
  INDEX idx_salesorder_no (salesorder_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE middleware_penjualan_cancel
  ADD COLUMN IF NOT EXISTS salesorder_id INT DEFAULT NULL AFTER order_no,
  ADD COLUMN IF NOT EXISTS salesorder_no VARCHAR(100) DEFAULT NULL AFTER salesorder_id,
  ADD COLUMN IF NOT EXISTS contact_id INT DEFAULT NULL AFTER salesorder_no,
  ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255) DEFAULT NULL AFTER contact_id,
  ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(50) DEFAULT NULL AFTER customer_name,
  ADD COLUMN IF NOT EXISTS customer_email VARCHAR(255) DEFAULT NULL AFTER customer_phone,
  ADD COLUMN IF NOT EXISTS transaction_date DATETIME DEFAULT NULL AFTER customer_email,
  ADD COLUMN IF NOT EXISTS created_date DATETIME DEFAULT NULL AFTER transaction_date,
  ADD COLUMN IF NOT EXISTS last_modified DATETIME DEFAULT NULL AFTER created_date,
  ADD COLUMN IF NOT EXISTS is_tax_included TINYINT(1) DEFAULT 0 AFTER last_modified,
  ADD COLUMN IF NOT EXISTS note TEXT DEFAULT NULL AFTER is_tax_included,
  ADD COLUMN IF NOT EXISTS sub_total DECIMAL(18,4) DEFAULT NULL AFTER note,
  ADD COLUMN IF NOT EXISTS total_disc DECIMAL(18,4) DEFAULT NULL AFTER sub_total,
  ADD COLUMN IF NOT EXISTS total_tax DECIMAL(18,4) DEFAULT NULL AFTER total_disc,
  ADD COLUMN IF NOT EXISTS grand_total DECIMAL(18,4) DEFAULT NULL AFTER total_tax,
  ADD COLUMN IF NOT EXISTS ref_no VARCHAR(100) DEFAULT NULL AFTER grand_total,
  ADD COLUMN IF NOT EXISTS payment_method VARCHAR(100) DEFAULT NULL AFTER ref_no,
  ADD COLUMN IF NOT EXISTS location_id INT DEFAULT NULL AFTER payment_method,
  ADD COLUMN IF NOT EXISTS is_canceled TINYINT(1) DEFAULT 0 AFTER location_id,
  ADD COLUMN IF NOT EXISTS cancel_reason_detail VARCHAR(255) DEFAULT NULL AFTER cancel_reason,
  ADD COLUMN IF NOT EXISTS source VARCHAR(100) DEFAULT NULL AFTER cancel_reason_detail,
  ADD COLUMN IF NOT EXISTS is_paid TINYINT(1) DEFAULT 0 AFTER source,
  ADD COLUMN IF NOT EXISTS channel_status VARCHAR(100) DEFAULT NULL AFTER is_paid,
  ADD COLUMN IF NOT EXISTS shipping_cost DECIMAL(18,4) DEFAULT NULL AFTER channel_status,
  ADD COLUMN IF NOT EXISTS insurance_cost DECIMAL(18,4) DEFAULT NULL AFTER shipping_cost,
  ADD COLUMN IF NOT EXISTS shipping_full_name VARCHAR(255) DEFAULT NULL AFTER insurance_cost,
  ADD COLUMN IF NOT EXISTS shipping_address VARCHAR(255) DEFAULT NULL AFTER shipping_full_name,
  ADD COLUMN IF NOT EXISTS shipping_area VARCHAR(150) DEFAULT NULL AFTER shipping_address,
  ADD COLUMN IF NOT EXISTS shipping_city VARCHAR(150) DEFAULT NULL AFTER shipping_area,
  ADD COLUMN IF NOT EXISTS shipping_province VARCHAR(150) DEFAULT NULL AFTER shipping_city,
  ADD COLUMN IF NOT EXISTS shipping_post_code VARCHAR(50) DEFAULT NULL AFTER shipping_province,
  ADD COLUMN IF NOT EXISTS shipping_country VARCHAR(100) DEFAULT NULL AFTER shipping_post_code,
  ADD COLUMN IF NOT EXISTS shipping_phone VARCHAR(50) DEFAULT NULL AFTER shipping_country,
  ADD COLUMN IF NOT EXISTS tracking_number VARCHAR(150) DEFAULT NULL AFTER shipping_phone,
  ADD COLUMN IF NOT EXISTS courier VARCHAR(150) DEFAULT NULL AFTER tracking_number,
  ADD COLUMN IF NOT EXISTS service_fee DECIMAL(18,4) DEFAULT NULL AFTER courier,
  ADD COLUMN IF NOT EXISTS buyer_shipping_cost DECIMAL(18,4) DEFAULT NULL AFTER service_fee,
  ADD COLUMN IF NOT EXISTS package_count INT DEFAULT NULL AFTER buyer_shipping_cost,
  ADD COLUMN IF NOT EXISTS wms_status VARCHAR(100) DEFAULT NULL AFTER package_count,
  ADD COLUMN IF NOT EXISTS shipping_cost_discount DECIMAL(18,4) DEFAULT NULL AFTER wms_status,
  ADD COLUMN IF NOT EXISTS discount_marketplace DECIMAL(18,4) DEFAULT NULL AFTER shipping_cost_discount,
  ADD COLUMN IF NOT EXISTS internal_cancel_date DATETIME DEFAULT NULL AFTER discount_marketplace,
  ADD COLUMN IF NOT EXISTS tracking_url VARCHAR(255) DEFAULT NULL AFTER internal_cancel_date,
  ADD COLUMN IF NOT EXISTS cod_fee DECIMAL(18,4) DEFAULT NULL AFTER tracking_url,
  ADD COLUMN IF NOT EXISTS total_weight_in_kg DECIMAL(18,4) DEFAULT NULL AFTER cod_fee,
  ADD COLUMN IF NOT EXISTS internal_status VARCHAR(100) DEFAULT NULL AFTER total_weight_in_kg,
  ADD COLUMN IF NOT EXISTS invoice_id INT DEFAULT NULL AFTER internal_status,
  ADD COLUMN IF NOT EXISTS invoice_no VARCHAR(100) DEFAULT NULL AFTER invoice_id,
  ADD COLUMN IF NOT EXISTS invoice_date DATETIME DEFAULT NULL AFTER invoice_no,
  ADD COLUMN IF NOT EXISTS salesmen_name VARCHAR(255) DEFAULT NULL AFTER invoice_date,
  ADD COLUMN IF NOT EXISTS tracking_no VARCHAR(150) DEFAULT NULL AFTER salesmen_name,
  ADD COLUMN IF NOT EXISTS source_name VARCHAR(100) DEFAULT NULL AFTER tracking_no,
  ADD COLUMN IF NOT EXISTS store_name VARCHAR(150) DEFAULT NULL AFTER source_name,
  ADD COLUMN IF NOT EXISTS location_name VARCHAR(150) DEFAULT NULL AFTER store_name,
  ADD COLUMN IF NOT EXISTS location_code VARCHAR(100) DEFAULT NULL AFTER location_name,
  ADD COLUMN IF NOT EXISTS picklist_no VARCHAR(100) DEFAULT NULL AFTER location_code,
  ADD COLUMN IF NOT EXISTS channel_id INT DEFAULT NULL AFTER picklist_no,
  ADD COLUMN IF NOT EXISTS store VARCHAR(100) DEFAULT NULL AFTER channel_id,
  ADD COLUMN IF NOT EXISTS items_payload LONGTEXT DEFAULT NULL AFTER payload;

ALTER TABLE middleware_penjualan_cancel_detail
  MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY cancel_id INT UNSIGNED NOT NULL;

ALTER TABLE middleware_penjualan_cancel_detail
  ADD CONSTRAINT fk_cancel_detail_header
    FOREIGN KEY (cancel_id)
    REFERENCES middleware_penjualan_cancel (id)
    ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS middleware_penjualan_cancel_item_serials (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cancel_id INT UNSIGNED NOT NULL,
  cancel_detail_id INT UNSIGNED NOT NULL,
  salesorder_detail_id BIGINT NULL,
  picked_serial_number_id BIGINT NULL,
  picklist_detail_id BIGINT NULL,
  pick_scanned_date DATETIME NULL,
  batch_no VARCHAR(255) NULL,
  serial_no VARCHAR(255) NULL,
  bin_id BIGINT NULL,
  qty INT NULL,
  expired_date DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_cancel_id (cancel_id),
  KEY idx_cancel_detail_id (cancel_detail_id),
  KEY idx_salesorder_detail_id (salesorder_detail_id),
  CONSTRAINT fk_cancel_item_serials_header
    FOREIGN KEY (cancel_id)
    REFERENCES middleware_penjualan_cancel (id)
    ON DELETE CASCADE,
  CONSTRAINT fk_cancel_item_serials_detail
    FOREIGN KEY (cancel_detail_id)
    REFERENCES middleware_penjualan_cancel_detail (id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
