<?php

namespace App\Controllers;

class ApiDocs extends BaseController
{
    public function initController($request, $response, $logger)
    {
        parent::initController($request, $response, $logger);
        helper('url');
    }

    public function index()
    {
        $endpoints = [
            [
                'method' => 'POST',
                'endpoint' => 'api/penjualan',
                'table' => 'middleware_penjualan',
                'description' => 'Insert transaksi penjualan',
                'required_fields' => ['salesorder_no'],
                'optional_fields' => ['invoice_no', 'grand_total', 'customer_name', 'shipping_address', 'courier', 'tracking_no'],
                'example_json' => json_encode([
                    [
                        'action' => 'update-salesorder',
                        'status' => 'INVOICED',
                        'salesorder_id' => 501038,
                        'salesorder_no' => 'SO-000501038',
                        'invoice_id' => 58851,
                        'invoice_no' => 'INV-000058851',
                        'invoice_date' => '2026-07-14T09:06:10.531Z',
                        'contact_id' => 39784,
                        'customer_name' => 'punyarahel',
                        'customer_phone' => '099xxx88',
                        'customer_email' => 'raheljube@jubelio.com',
                        'transaction_date' => '2026-07-14T09:06:10.531Z',
                        'created_date' => '2026-07-14T09:06:11.073Z',
                        'last_modified' => '2026-07-15T08:04:04.105Z',
                        'internal_status' => 'PROCESSING',
                        'channel_status' => 'Processing',
                        'source' => 'INTERNAL',
                        'source_name' => 'INTERNAL',
                        'store' => 'Toko Default',
                        'store_name' => 'Toko Default',
                        'store_id' => -100,
                        'location_id' => -1,
                        'location_name' => 'Pusat',
                        'location_code' => '123',
                        'sub_total' => '67000.0000',
                        'total_disc' => '0.0000',
                        'total_tax' => '0.0000',
                        'grand_total' => '67000.0000',
                        'shipping_cost' => '0.0000',
                        'insurance_cost' => '0.0000',
                        'shipping_tax' => '0.0000',
                        'shipping_cost_discount' => '0.0000',
                        'buyer_shipping_cost' => '0.0000',
                        'shipping_full_name' => 'o',
                        'shipping_phone' => '099xxx88',
                        'shipping_address' => 'Jalan MCC',
                        'shipping_area' => '',
                        'shipping_city' => '',
                        'shipping_province' => '',
                        'shipping_post_code' => '',
                        'shipping_country' => '',
                        'courier' => 'Teman Express',
                        'shipper' => 'Teman Express',
                        'tracking_no' => '',
                        'tracking_number' => null,
                        'tracking_url' => null,
                        'picklist_no' => 'PICK-000011225',
                        'picked_in' => 11225,
                        'wms_status' => 'FINISH_PACK',
                        'total_weight_in_kg' => '2.150',
                        'is_paid' => true,
                        'is_tax_included' => false,
                        'is_acknowledge' => true,
                        'is_label_printed' => true,
                        'label_printed_count' => 1,
                        'package_count' => 1,
                        'is_cod' => false,
                        'is_shipped' => null,
                        'use_shipping_insurance' => false,
                        'items' => [
                            [
                                'salesorder_detail_id' => 62507,
                                'item_id' => 18885,
                                'item_code' => '!POHON2',
                                'item_name' => 'POHON racul kiyowo',
                                'description' => 'POHON racul kiyowo',
                                'barcode' => '4905083062197',
                                'qty' => '1.0000',
                                'qty_in_base' => '1.0000',
                                'unit' => 'Buah',
                                'uom_id' => null,
                                'price' => '11000.0000',
                                'sell_price' => '11000.0000',
                                'original_price' => '11000.0000',
                                'amount' => '11000.0000',
                                'disc' => '0.00',
                                'disc_amount' => '0.0000',
                                'disc_marketplace' => '0.0000',
                                'tax_id' => 1,
                                'tax_name' => 'No Tax',
                                'tax_amount' => '0.0000',
                                'rate' => '0.00',
                                'weight_in_gram' => '450.0000',
                                'item_group_id' => 10267,
                                'loc_id' => -1,
                                'loc_name' => 'Pusat',
                                'thumbnail' => 'https://file-service.3smqg.upcloudobjects.com/images/ndnmuriwr1sspttrd3ddig/ec625bef-afeb-473c-a00a-66093ee4280a_thumb.jpeg',
                                'is_bundle' => false,
                                'is_fbm' => false,
                                'fbm' => '',
                                'serials' => []
                            ],
                            [
                                'salesorder_detail_id' => 62508,
                                'item_id' => 18886,
                                'item_code' => '!PUPUK1',
                                'item_name' => 'Pupuk Organik Premium',
                                'description' => 'Pupuk Organik Premium',
                                'barcode' => '8991234567890',
                                'qty' => '2.0000',
                                'qty_in_base' => '2.0000',
                                'unit' => 'Sak',
                                'uom_id' => null,
                                'price' => '15000.0000',
                                'sell_price' => '15000.0000',
                                'original_price' => '15000.0000',
                                'amount' => '30000.0000',
                                'disc' => '0.00',
                                'disc_amount' => '0.0000',
                                'disc_marketplace' => '0.0000',
                                'tax_id' => 1,
                                'tax_name' => 'No Tax',
                                'tax_amount' => '0.0000',
                                'rate' => '0.00',
                                'weight_in_gram' => '500.0000',
                                'item_group_id' => 10267,
                                'loc_id' => -1,
                                'loc_name' => 'Pusat',
                                'thumbnail' => '',
                                'is_bundle' => false,
                                'is_fbm' => false,
                                'fbm' => '',
                                'serials' => []
                            ],
                            [
                                'salesorder_detail_id' => 62509,
                                'item_id' => 18887,
                                'item_code' => '!POT001',
                                'item_name' => 'Pot Tanaman Besar',
                                'description' => 'Pot Tanaman Besar',
                                'barcode' => '8999876543210',
                                'qty' => '2.0000',
                                'qty_in_base' => '2.0000',
                                'unit' => 'Buah',
                                'uom_id' => null,
                                'price' => '13000.0000',
                                'sell_price' => '13000.0000',
                                'original_price' => '13000.0000',
                                'amount' => '26000.0000',
                                'disc' => '0.00',
                                'disc_amount' => '0.0000',
                                'disc_marketplace' => '0.0000',
                                'tax_id' => 1,
                                'tax_name' => 'No Tax',
                                'tax_amount' => '0.0000',
                                'rate' => '0.00',
                                'weight_in_gram' => '600.0000',
                                'item_group_id' => 10267,
                                'loc_id' => -1,
                                'loc_name' => 'Pusat',
                                'thumbnail' => '',
                                'is_bundle' => false,
                                'is_fbm' => false,
                                'fbm' => '',
                                'serials' => []
                            ]
                        ],
                        'extra_info' => [],
                        'extra_info_header' => []
                    ]
                ], JSON_PRETTY_PRINT)
            ],
            [
                'method' => 'POST',
                'endpoint' => 'api/penjualan-cancel',
                'table' => 'middleware_penjualan_cancel',
                'description' => 'Insert penjualan cancel',
                'required_fields' => ['salesorder_no'],
                'optional_fields' => ['cancel_reason', 'cancel_date', 'items', 'shipping_address', 'wms_status'],
                'example_json' => json_encode([
                    [
                        'action' => 'update-salesorder',
                        'items' => [],
                    ]
                ], JSON_PRETTY_PRINT)
            ],
            [
                'method' => 'POST',
                'endpoint' => 'api/bill-with-putaway-true',
                'table' => 'middleware_bill_with_putaway_true',
                'description' => 'Insert bill with putaway true payload',
                'required_fields' => ['bill_no'],
                'optional_fields' => ['supplier_name', 'transaction_date', 'due_date', 'items', 'is_putaway'],
                'example_json' => json_encode([
                    [
                        'bill_id' => 12345,
                        'bill_no' => 'BILL-0001',
                        'contact_id' => 54321,
                        'supplier_name' => 'Supplier A',
                        'transaction_date' => '2026-07-21T05:57:28.000Z',
                        'created_date' => '2026-07-21T05:57:28.000Z',
                        'due_date' => '2026-08-21T00:00:00.000Z',
                        'is_tax_included' => true,
                        'note' => 'Catatan bill',
                        'sub_total' => '100000.0000',
                        'total_disc' => '5000.0000',
                        'total_tax' => '9000.0000',
                        'grand_total' => '104000.0000',
                        'ref_no' => 'REF-123',
                        'is_opening_balance' => false,
                        'payment' => '104000.0000',
                        'payment_acct_id' => 987,
                        'location_id' => -1,
                        'purchaseorder_id' => 4567,
                        'last_modified' => '2026-07-21T06:00:00.000Z',
                        'is_consignment' => false,
                        'created_by' => 'admin',
                        'payment_term' => '30 days',
                        'auto_placement' => true,
                        'attachment' => null,
                        'add_cost' => '0.0000',
                        'updated_by' => 'admin',
                        'tag_ids' => [],
                        'header_note' => 'Header note',
                        'is_closed' => false,
                        'purchaseorder_no' => 'PO-001',
                        'location_name' => 'Pusat',
                        'payment_amount' => '104000.0000',
                        'add_cost_detail' => [],
                        'is_putaway' => true,
                        'items' => []
                    ]
                ], JSON_PRETTY_PRINT)
            ],
        ];

        $data = [
            'title' => 'Dokumentasi API',
            'endpoints' => $endpoints,
        ];

        return view('api_documentation', $data);
    }
}
